name: Validate Renovate config

on:
  push:
    paths:
      - .github/renovate.json
  pull_request:
    paths:
      - .github/renovate.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate renovate.json
        uses: tj-actions/renovate-config-validator@v2
        with:
          config_file: .github/renovate.json
